
ibex_base = {
    "config_name": "ibex_base",

    "rtl_files": [
        "rtl/ibex_pkg.sv",
        # "rtl/ibex_tracer_pkg.sv",
        # "rtl/ibex_tracer.sv",
        "rtl/ibex_alu.sv",
        "rtl/ibex_branch_predict.sv",
        "rtl/ibex_compressed_decoder.sv",
        "rtl/ibex_controller.sv",
        "rtl/ibex_csr.sv",
        "rtl/ibex_cs_registers.sv",
        "rtl/ibex_counter.sv",
        "rtl/ibex_decoder.sv",
        "rtl/ibex_dummy_instr.sv",
        "rtl/ibex_ex_block.sv",
        "rtl/ibex_wb_stage.sv",
        "rtl/ibex_id_stage.sv",
        "rtl/ibex_icache.sv",
        "rtl/ibex_if_stage.sv",
        "rtl/ibex_load_store_unit.sv",
        "rtl/ibex_lockstep.sv",
        "rtl/ibex_multdiv_slow.sv",
        "rtl/ibex_multdiv_fast.sv",
        "rtl/ibex_prefetch_buffer.sv",
        "rtl/ibex_fetch_fifo.sv",
        "rtl/ibex_register_file_ff.sv",
        "rtl/ibex_register_file_fpga.sv",
        "rtl/ibex_register_file_latch.sv",
        "rtl/ibex_pmp.sv",
        "rtl/ibex_core.sv",
        "rtl/ibex_top.sv",
        # "rtl/ibex_top_tracing.sv",
    ],

    "rtl_incdirs": [
        "rtl"
    ],

    "rtl_dependencies": ["ibex_prim"],

    "tb_files": [
        "vendor/google_riscv-dv/src/riscv_signature_pkg.sv",
        "dv/uvm/bus_params_pkg/bus_params_pkg.sv",
        "dv/sv/common_ifs/clk_rst_if.sv",
        "dv/sv/common_ifs/pins_if.sv",
        "dv/sv/str_utils/str_utils_pkg.sv",
        "dv/sv/dv_utils/dv_test_status_pkg.sv",
        "dv/sv/dv_utils/dv_utils_pkg.sv",
        "dv/sv/dv_base_reg/dv_base_reg_pkg.sv",
        "dv/sv/csr_utils/csr_utils_pkg.sv",
        "dv/sv/dv_lib/dv_lib_pkg.sv",
        "dv/sv/mem_model/mem_model_pkg.sv",
        "dv/sv/push_pull_agent/push_pull_if.sv",
        "dv/sv/push_pull_agent/push_pull_agent_pkg.sv",
        "dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf.sv",
        "dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_pkg.sv",
        "dv/uvm/core_ibex/common/irq_agent/irq_if.sv",
        "dv/uvm/core_ibex/common/irq_agent/irq_agent_pkg.sv",
        "dv/uvm/core_ibex/env/core_ibex_rvfi_if.sv",
        "dv/uvm/core_ibex/common/ibex_cosim_agent/core_ibex_ifetch_if.sv",
        "dv/uvm/core_ibex/common/ibex_cosim_agent/core_ibex_ifetch_pmp_if.sv",
        "dv/uvm/core_ibex/common/ibex_cosim_agent/ibex_cosim_agent_pkg.sv",
        "dv/uvm/core_ibex/common/ibex_mem_intf_agent/ibex_mem_intf_agent_pkg.sv",
        "dv/uvm/core_ibex/env/core_ibex_instr_monitor_if.sv",
        "dv/uvm/core_ibex/env/core_ibex_dut_probe_if.sv",
        "dv/uvm/core_ibex/env/core_ibex_csr_if.sv",
        "dv/uvm/core_ibex/env/core_ibex_env_pkg.sv",
        "dv/uvm/core_ibex/tests/core_ibex_test_pkg.sv",
        "dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv",
        "dv/uvm/core_ibex/fcov/core_ibex_fcov_bind.sv",
        "dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv",
        "dv/uvm/core_ibex/tb/core_ibex_tb_top.sv",
    ],

    "tb_incdirs": [],

    "tb_dependencies": [],

    "verilog_wrapper": "",
}
